// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace NIST_Calibration_Sheet.Models
{
    public partial class AmbientResult
    {
        public string LaserSerialNo { get; set; }
        public string LaserType { get; set; }
        public int? Cell { get; set; }
        public DateTime? TestDate { get; set; }
        public bool? SecondGas { get; set; }
        public string Result { get; set; }
        public string Notes { get; set; }
        public double? ZeroActual { get; set; }
        public double? ZeroAverage { get; set; }
        public double? ZeroMinimum { get; set; }
        public double? ZeroMaximum { get; set; }
        public double? MidActual { get; set; }
        public double? MidAverage { get; set; }
        public double? MidMinimum { get; set; }
        public double? MidMaximum { get; set; }
        public double? SpanActual { get; set; }
        public double? SpanAverage { get; set; }
        public double? SpanMinimum { get; set; }
        public double? SpanMaximum { get; set; }
        public double? Mid2Actual { get; set; }
        public double? Mid2Average { get; set; }
        public double? Mid2Minimum { get; set; }
        public double? Mid2Maximum { get; set; }
        public double? Span2Actual { get; set; }
        public double? Span2Average { get; set; }
        public double? Span2Minimum { get; set; }
        public double? Span2Maximum { get; set; }
    }
}