//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NIST_Calibration_Sheet__Final.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.6.0.0")]
    internal sealed partial class ConnectionSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static ConnectionSettings defaultInstance = ((ConnectionSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new ConnectionSettings())));
        
        public static ConnectionSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=SQLSV800-002;Initial Catalog=\"\"GasCheckTDLS\"\";Persist Security Info=T" +
            "rue;User ID=Generic_mfg;Password=55555")]
        public string GasCheckTDLSConnectionString {
            get {
                return ((string)(this["GasCheckTDLSConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\\\\\svr300-003\\\\MFG\\\\Databases\\\\Orders\\\\0000-005671-0023.txt")]
        public string SapFolderPath {
            get {
                return ((string)(this["SapFolderPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\\\\\svr300-003\\\\MFG\\\\Databases\\\\LAD Newnan\\\\FIT_DATA\\\\Result_Data\\\\Result_Log")]
        public string TotalResultLogPath {
            get {
                return ((string)(this["TotalResultLogPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\\\\\svr300-003\\\\MFG\\\\Databases\\\\LAD Newnan\\\\FIT_DATA\\\\Result_Data\\\\Result_QIC\\\\TD" +
            "LS8000")]
        public string QICSearchPath {
            get {
                return ((string)(this["QICSearchPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\\\\\svr300-003\\\\MFG\\\\Databases\\\\LAD Newnan\\\\FIT_DATA\\\\Result_Data\\\\M1202JHZ911T1_" +
            "TDLS8000 NIST Traceable Calibration Certificatej.xlsx")]
        public string ExcelFilePath {
            get {
                return ((string)(this["ExcelFilePath"]));
            }
        }
    }
}
